"""SQLAlchemy declarative base and shared column types.

The ORM models live in ``cascade.storage.models``. They are deliberately separate from
the Pydantic value objects in ``cascade.domain`` — the storage schema can evolve
independently from the wire format, and converters in ``cascade.storage.repositories``
translate between them.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, mapped_column

# Naming convention used by Alembic for generating constraint names. Without this,
# autogenerated migrations create unstable names that drift between SQLite and Postgres.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# Reusable column annotations -----------------------------------------------------

uuid_pk = Annotated[
    UUID,
    mapped_column(PG_UUID(as_uuid=True), primary_key=True),
]

uuid_fk = Annotated[
    UUID,
    mapped_column(PG_UUID(as_uuid=True), nullable=False),
]

created_at = Annotated[
    datetime,
    mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    ),
]

updated_at = Annotated[
    datetime,
    mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    ),
]
